job ('Maven-Project-Via-DSL') {
    description ("First maven job generated by DSL on ${new Date()}")
    scm {
        git ("https://github.com/gauravthakur02/Jenkins_UpgradeV3.git", main)
    }
    triggers {
        scm ('* * * * *')
    }
    steps {
        maven ('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
